# Generated by Django 5.0.3 on 2024-03-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='roll',
            new_name='id',
        ),
    ]
