# Generated by Django 5.0.3 on 2024-03-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_roll_userdetails_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='id',
            new_name='id_1',
        ),
    ]
