# Generated by Django 5.0.3 on 2024-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_id_userdetails_id_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_code', models.IntegerField(max_length=100)),
                ('b_code', models.IntegerField(max_length=100)),
                ('issue_date', models.IntegerField(max_length=100)),
                ('return_date', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'BookInfo',
            },
        ),
    ]
