# Generated by Django 5.0.3 on 2024-03-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='b_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='issue_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='return_date',
            field=models.CharField(max_length=100),
        ),
    ]
